services:
  - type: web
    name: timerrr
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn --threads 4 -w 1 --bind 0.0.0.0:$PORT run:app"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: sqlite:///timerrr.db